apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-app
spec:
  selector:
    matchLabels:
      app: zipkin-app
  template:
    metadata:
      labels:
        app: zipkin-app
    spec:
      containers:
      - name: zipkin-app
        image: openzipkin/zipkin
        imagePullPolicy: Always
        ports:
        - containerPort: 9411

---

apiVersion: v1
kind: Service
metadata:
  name: zipkin-svc
spec:
  selector:
    app: zipkin-app
  ports:
  - port: 9411
    targetPort: 9411

---

apiVersion: v1
kind: Service
metadata:
  name: zipkin-lb-svc
spec:
  type: LoadBalancer
  selector:
    app: zipkin-app
  ports:
  - port: 9411
    targetPort: 9411


