server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:34.100.189.145}:3306/payments_db
    username: root
    password: root@123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9296}